In [9]:
import time
import datetime
import calendar
import pytz

import numpy as np
import pandas as pd

# 一、pandas TimeSeries APIs:

### 1. Timestamp - `pd.Timestamp()`

In [10]:
datetime.datetime(2019, 8, 21)

datetime.datetime(2019, 8, 21, 0, 0)

In [11]:
pd.Timestamp(datetime.datetime(2019, 8, 21))

Timestamp('2019-08-21 00:00:00')

In [12]:
pd.Timestamp("2019-08-21")

Timestamp('2019-08-21 00:00:00')

In [13]:
pd.Timestamp(2019, 8, 21)

Timestamp('2019-08-21 00:00:00')

In [14]:
day = pd.Timestamp(2019, 8, 21)
print(day.day_name())

Wednesday

### 2. Period - `pd.Period()`

In [15]:
pd.Period("2019-08")

Period('2019-08', 'M')

In [16]:
pd.Period("2019-08", freq = "D")

Period('2019-08-01', 'D')

### 3. Timestamp & Period as index

#### 3.1 DatetimeIndex

In [36]:
dates = [pd.Timestamp("2019-08-21"), pd.Timestamp("2019-08-22"), pd.Timestamp("2019-08-23")]
ts = pd.Series(np.random.randn(3), index = dates)
print(ts)
print("-" * 25)
print(ts.index)
print("-" * 25)
print(type(ts.index))

2019-08-21   -0.195642
2019-08-22    0.433605
2019-08-23    0.519007
dtype: float64
-------------------------
DatetimeIndex(['2019-08-21', '2019-08-22', '2019-08-23'], dtype='datetime64[ns]', freq=None)
-------------------------
<class 'pandas.core.indexes.datetimes.DatetimeIndex'>

#### 3.2 PeriodIndex

In [37]:
periods = [pd.Period("2019-08"), pd.Period("2019-07"), pd.Period("2019-06")]
ts = pd.Series(np.random.randn(3), index = periods)
print(ts)
print("-" * 20)
print(ts.index)
print("-" * 20)
print(type(ts.index))

2019-08   -0.999400
2019-07   -0.213444
2019-06   -1.463501
Freq: M, dtype: float64
--------------------
PeriodIndex(['2019-08', '2019-07', '2019-06'], dtype='period[M]', freq='M')
--------------------
<class 'pandas.core.indexes.period.PeriodIndex'>

### 4. To Timestamp

* `pd.to_datetime(pd.Series/List, dayfirst, format, errors, unit, origin)`

In [39]:
# series
s = pd.Series(["Jul 31, 2009", "2010-01-10", None])
ts  = pd.to_datetime(s)
print(ts)

0   2009-07-31
1   2010-01-10
2          NaT
dtype: datetime64[ns]

In [42]:
# list
l = ["2005/11/23", "2010-12-31"]
tl = pd.to_datetime(l)
print(tl)

DatetimeIndex(['2005-11-23', '2010-12-31'], dtype='datetime64[ns]', freq=None)

In [45]:
d = ["04-01-2012 10:00"]
td1 = pd.to_datetime(d)
td2 = pd.to_datetime(d, dayfirst = True)
print(td1)
print(td2)
print("-" * 80)
d2 = ["14-01-2019", "01-14-2019"]
td3 = pd.to_datetime(d2)
td4 = pd.to_datetime(d2, dayfirst = True)
print(td3)
print(td4)

DatetimeIndex(['2012-04-01 10:00:00'], dtype='datetime64[ns]', freq=None)
DatetimeIndex(['2012-01-04 10:00:00'], dtype='datetime64[ns]', freq=None)
--------------------------------------------------------------------------------
DatetimeIndex(['2019-01-14', '2019-01-14'], dtype='datetime64[ns]', freq=None)
DatetimeIndex(['2019-01-14', '2019-01-14'], dtype='datetime64[ns]', freq=None)

In [22]:
print(pd.to_datetime("2010/11/12", format = "%Y/%m/%d"))
print(pd.to_datetime("12-11-2010 00:00", format = "%d-%m-%Y %H:%M"))

2010-11-12 00:00:00
2010-11-12 00:00:00

In [23]:
df = pd.DataFrame({
    "year": [2015, 2016],
    "month": [2, 3],
    "day": [4, 5],
    "hour": [2, 3]
})
print(df)
print()
print(pd.to_datetime(df))
print()
print(pd.to_datetime(df[["year", "month", "day"]]))

   year  month  day  hour
0  2015      2    4     2
1  2016      3    5     3

0   2015-02-04 02:00:00
1   2016-03-05 03:00:00
dtype: datetime64[ns]

0   2015-02-04
1   2016-03-05
dtype: datetime64[ns]

In [24]:
try:
    pd.to_datetime(["2019-08-21", "asd"], errors = "raise")
except ValueError as e:
    print(e)

print(pd.to_datetime(["2019-08-21", "asd"], errors = "ignore"))
print(pd.to_datetime(["2019-08-21", "asd"], errors = "coerce"))

('Unknown string format:', 'asd')
['2019-08-21' 'asd']
DatetimeIndex(['2019-08-21', 'NaT'], dtype='datetime64[ns]', freq=None)

In [48]:
# to_datetime() 中传入了List
print(pd.to_datetime([1349720105, 1349806505, 1349892905, 1349979305, 1350065705], unit = "s"))
print(pd.to_datetime([1349720105000, 1349806505000, 1349892905000, 1349979305000, 1350065705000], unit = "ms"))
print(pd.to_datetime([1262347200000000000]).tz_localize("US/Pacific"))
print(pd.to_datetime([1262347200000000000]).tz_localize("UTC"))
print(pd.DatetimeIndex([1262347200000000000]).tz_localize("US/Pacific"))

DatetimeIndex(['2012-10-08 18:15:05', '2012-10-09 18:15:05',
               '2012-10-10 18:15:05', '2012-10-11 18:15:05',
               '2012-10-12 18:15:05'],
              dtype='datetime64[ns]', freq=None)
DatetimeIndex(['2012-10-08 18:15:05', '2012-10-09 18:15:05',
               '2012-10-10 18:15:05', '2012-10-11 18:15:05',
               '2012-10-12 18:15:05'],
              dtype='datetime64[ns]', freq=None)
DatetimeIndex(['2010-01-01 12:00:00-08:00'], dtype='datetime64[ns, US/Pacific]', freq=None)
DatetimeIndex(['2010-01-01 12:00:00+00:00'], dtype='datetime64[ns, UTC]', freq=None)
DatetimeIndex(['2010-01-01 12:00:00-08:00'], dtype='datetime64[ns, US/Pacific]', freq=None)

In [26]:
print(pd.to_datetime([1, 2, 3], unit = "D", origin = pd.Timestamp('1960-01-01')))
print(pd.to_datetime([1, 2, 3], unit = "D"))

DatetimeIndex(['1960-01-02', '1960-01-03', '1960-01-04'], dtype='datetime64[ns]', freq=None)
DatetimeIndex(['1970-01-02', '1970-01-03', '1970-01-04'], dtype='datetime64[ns]', freq=None)

### 5. Range of Timestamp

* `pd.date_range(start, end, freq, period)`
* `pd.bdate_range(start, end, freq, period)`

In [54]:
start = datetime.datetime(2018, 1, 1)
end = datetime.datetime(2019, 1, 1)

In [62]:
print(pd.date_range(start, end))  # Calendar day 
print(pd.bdate_range(start, end)) # Business day
print("-" * 100)
print(pd.date_range(start, periods = 1000, freq = "M"))   # Month End
print(pd.bdate_range(start, periods = 250, freq = "BQS")) # Business Quarter Start
print("-" * 100)
print(pd.date_range(start, end, freq = "BM")) # Business Month End
print(pd.date_range(start, end, freq = "W")) # Weekly
print("-" * 100)
print(pd.date_range(end = end, periods = 20))     # end and length
print(pd.date_range(start = start, periods = 20)) # start and length
print("-" * 100)
print(pd.date_range("2018-01-01", "2018-01-05", periods = 5)) # start and end and length
print(pd.date_range("2018-01-01", "2018-01-05", periods = 10))# start and end and length

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-06', '2018-01-07', '2018-01-08',
               '2018-01-09', '2018-01-10',
               ...
               '2018-12-23', '2018-12-24', '2018-12-25', '2018-12-26',
               '2018-12-27', '2018-12-28', '2018-12-29', '2018-12-30',
               '2018-12-31', '2019-01-01'],
              dtype='datetime64[ns]', length=366, freq='D')
DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-08', '2018-01-09', '2018-01-10',
               '2018-01-11', '2018-01-12',
               ...
               '2018-12-19', '2018-12-20', '2018-12-21', '2018-12-24',
               '2018-12-25', '2018-12-26', '2018-12-27', '2018-12-28',
               '2018-12-31', '2019-01-01'],
              dtype='datetime64[ns]', length=262, freq='B')
----------------------------------------------------------------------------------------------------
DatetimeIndex(['2018-01-31', '2018-02-28', '2018-03-31', '2018-04-30',
               '2018-05-31', '2018-06-30', '2018-07-31', '2018-08-31',
               '2018-09-30', '2018-10-31',
               ...
               '2100-07-31', '2100-08-31', '2100-09-30', '2100-10-31',
               '2100-11-30', '2100-12-31', '2101-01-31', '2101-02-28',
               '2101-03-31', '2101-04-30'],
              dtype='datetime64[ns]', length=1000, freq='M')
DatetimeIndex(['2018-01-01', '2018-04-02', '2018-07-02', '2018-10-01',
               '2019-01-01', '2019-04-01', '2019-07-01', '2019-10-01',
               '2020-01-01', '2020-04-01',
               ...
               '2078-01-03', '2078-04-01', '2078-07-01', '2078-10-03',
               '2079-01-02', '2079-04-03', '2079-07-03', '2079-10-02',
               '2080-01-01', '2080-04-01'],
              dtype='datetime64[ns]', length=250, freq='BQS-JAN')
----------------------------------------------------------------------------------------------------
DatetimeIndex(['2018-01-31', '2018-02-28', '2018-03-30', '2018-04-30',
               '2018-05-31', '2018-06-29', '2018-07-31', '2018-08-31',
               '2018-09-28', '2018-10-31', '2018-11-30', '2018-12-31'],
              dtype='datetime64[ns]', freq='BM')
DatetimeIndex(['2018-01-07', '2018-01-14', '2018-01-21', '2018-01-28',
               '2018-02-04', '2018-02-11', '2018-02-18', '2018-02-25',
               '2018-03-04', '2018-03-11', '2018-03-18', '2018-03-25',
               '2018-04-01', '2018-04-08', '2018-04-15', '2018-04-22',
               '2018-04-29', '2018-05-06', '2018-05-13', '2018-05-20',
               '2018-05-27', '2018-06-03', '2018-06-10', '2018-06-17',
               '2018-06-24', '2018-07-01', '2018-07-08', '2018-07-15',
               '2018-07-22', '2018-07-29', '2018-08-05', '2018-08-12',
               '2018-08-19', '2018-08-26', '2018-09-02', '2018-09-09',
               '2018-09-16', '2018-09-23', '2018-09-30', '2018-10-07',
               '2018-10-14', '2018-10-21', '2018-10-28', '2018-11-04',
               '2018-11-11', '2018-11-18', '2018-11-25', '2018-12-02',
               '2018-12-09', '2018-12-16', '2018-12-23', '2018-12-30'],
              dtype='datetime64[ns]', freq='W-SUN')
----------------------------------------------------------------------------------------------------
DatetimeIndex(['2018-12-13', '2018-12-14', '2018-12-15', '2018-12-16',
               '2018-12-17', '2018-12-18', '2018-12-19', '2018-12-20',
               '2018-12-21', '2018-12-22', '2018-12-23', '2018-12-24',
               '2018-12-25', '2018-12-26', '2018-12-27', '2018-12-28',
               '2018-12-29', '2018-12-30', '2018-12-31', '2019-01-01'],
              dtype='datetime64[ns]', freq='D')
DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-06', '2018-01-07', '2018-01-08',
               '2018-01-09', '2018-01-10', '2018-01-11', '2018-01-12',
               '2018-01-13', '2018-01-14', '2018-01-15', '2018-01-16',
               '2018-01-17', '2018-01-18', '2018-01-19', '2018-01-20'],
              dtype='datetime64[ns]', freq='D')
----------------------------------------------------------------------------------------------------
DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05'],
              dtype='datetime64[ns]', freq=None)
DatetimeIndex(['2018-01-01 00:00:00', '2018-01-01 10:40:00',
               '2018-01-01 21:20:00', '2018-01-02 08:00:00',
               '2018-01-02 18:40:00', '2018-01-03 05:20:00',
               '2018-01-03 16:00:00', '2018-01-04 02:40:00',
               '2018-01-04 13:20:00', '2018-01-05 00:00:00'],
              dtype='datetime64[ns]', freq=None)

In [61]:
weekmask = "Mon Wed Fri"
holidays = [datetime.datetime(2011, 1, 5), datetime.datetime(2011, 3, 14)]
idx1 = pd.bdate_range(start, end, freq = "C", weekmask = weekmask, holidays = holidays)
print(idx1)
idx2 = pd.bdate_range(start, end, freq = "CBMS", weekmask = weekmask)
print(idx2)

DatetimeIndex(['2018-01-01', '2018-01-03', '2018-01-05', '2018-01-08',
               '2018-01-10', '2018-01-12', '2018-01-15', '2018-01-17',
               '2018-01-19', '2018-01-22',
               ...
               '2018-12-10', '2018-12-12', '2018-12-14', '2018-12-17',
               '2018-12-19', '2018-12-21', '2018-12-24', '2018-12-26',
               '2018-12-28', '2018-12-31'],
              dtype='datetime64[ns]', length=157, freq='C')
DatetimeIndex(['2018-01-01', '2018-02-02', '2018-03-02', '2018-04-02',
               '2018-05-02', '2018-06-01', '2018-07-02', '2018-08-01',
               '2018-09-03', '2018-10-01', '2018-11-02', '2018-12-03'],
              dtype='datetime64[ns]', freq='CBMS')

In [30]:
print(pd.Timestamp.min)
print(pd.Timestamp.max)

1677-09-21 00:12:43.145225
2262-04-11 23:47:16.854775807

### 6. Timestamp Index —— DatetimeIndex

In [64]:
start = datetime.datetime(2011, 1, 1)
end = datetime.datetime(2012, 1, 1)
rng = pd.date_range(start, end, freq = "BM") # Business Month 
ts = pd.Series(np.random.randn(len(rng)), index = rng)
print(ts)
print("-" * 100)
print(ts.index)
print("-" * 100)
print(ts[:5].index)
print("-" * 100)
print(ts[::2].index)
print("-" * 100)
print(ts["1/31/2011"])
print("-" * 100)
print(ts[datetime.datetime(2011, 12, 25):])
print("-" * 100)
print(ts['10/31/2011':'12/31/2011'])
print("-" * 100)
print(ts["2011"])
print("-" * 100)
print(ts["2011-6"])

2011-01-31    0.341942
2011-02-28    0.859577
2011-03-31    0.985406
2011-04-29   -0.224811
2011-05-31   -0.888166
2011-06-30    0.710712
2011-07-29    0.355943
2011-08-31   -2.422465
2011-09-30   -0.769204
2011-10-31    1.886651
2011-11-30    0.456291
2011-12-30    1.312205
Freq: BM, dtype: float64
----------------------------------------------------------------------------------------------------
DatetimeIndex(['2011-01-31', '2011-02-28', '2011-03-31', '2011-04-29',
               '2011-05-31', '2011-06-30', '2011-07-29', '2011-08-31',
               '2011-09-30', '2011-10-31', '2011-11-30', '2011-12-30'],
              dtype='datetime64[ns]', freq='BM')
----------------------------------------------------------------------------------------------------
DatetimeIndex(['2011-01-31', '2011-02-28', '2011-03-31', '2011-04-29',
               '2011-05-31'],
              dtype='datetime64[ns]', freq='BM')
----------------------------------------------------------------------------------------------------
DatetimeIndex(['2011-01-31', '2011-03-31', '2011-05-31', '2011-07-29',
               '2011-09-30', '2011-11-30'],
              dtype='datetime64[ns]', freq='2BM')
----------------------------------------------------------------------------------------------------
0.3419422485361135
----------------------------------------------------------------------------------------------------
2011-12-30    1.312205
Freq: BM, dtype: float64
----------------------------------------------------------------------------------------------------
2011-10-31    1.886651
2011-11-30    0.456291
2011-12-30    1.312205
Freq: BM, dtype: float64
----------------------------------------------------------------------------------------------------
2011-01-31    0.341942
2011-02-28    0.859577
2011-03-31    0.985406
2011-04-29   -0.224811
2011-05-31   -0.888166
2011-06-30    0.710712
2011-07-29    0.355943
2011-08-31   -2.422465
2011-09-30   -0.769204
2011-10-31    1.886651
2011-11-30    0.456291
2011-12-30    1.312205
Freq: BM, dtype: float64
----------------------------------------------------------------------------------------------------
2011-06-30    0.710712
Freq: BM, dtype: float64

In [21]:
print(pd.DatetimeIndex(["2018-01-01", "2018-01-03", "2018-01-05"]))
print(pd.DatetimeIndex(["2018-01-01", "2018-01-03", "2018-01-05"], freq = "infer"))

DatetimeIndex(['2018-01-01', '2018-01-03', '2018-01-05'], dtype='datetime64[ns]', freq=None)
DatetimeIndex(['2018-01-01', '2018-01-03', '2018-01-05'], dtype='datetime64[ns]', freq='2D')

In [65]:
dft = pd.DataFrame(np.random.randn(100000, 1),
                   columns = ["A"],
                   index = pd.date_range("20130101", periods = 100000, freq = "T")) # minutely 
print(dft)
print("-" * 100)
print(dft["2013"])
print("-" * 100)
print(dft["2013-1":"2013-2"])
print("-" * 100)
print(dft["2013-1":"2013-2-28"])
print("-" * 100)
print(dft["2013-1":"2013-2-28 00:00:00"])
print("-" * 100)
print(dft["2013-1-15":"2013-1-15 12:30:00"])

                            A
2013-01-01 00:00:00 -0.242536
2013-01-01 00:01:00  0.548547
2013-01-01 00:02:00 -1.117038
2013-01-01 00:03:00  0.432176
2013-01-01 00:04:00 -0.510630
2013-01-01 00:05:00 -0.957357
2013-01-01 00:06:00  0.965401
2013-01-01 00:07:00 -1.400734
2013-01-01 00:08:00  0.578109
2013-01-01 00:09:00 -0.655137
2013-01-01 00:10:00 -1.963523
2013-01-01 00:11:00  1.283547
2013-01-01 00:12:00  1.595535
2013-01-01 00:13:00 -0.881298
2013-01-01 00:14:00 -0.100967
2013-01-01 00:15:00  0.090259
2013-01-01 00:16:00  0.776400
2013-01-01 00:17:00  0.421742
2013-01-01 00:18:00  0.240029
2013-01-01 00:19:00  0.759932
2013-01-01 00:20:00 -0.121517
2013-01-01 00:21:00  1.081618
2013-01-01 00:22:00 -0.212912
2013-01-01 00:23:00  0.184384
2013-01-01 00:24:00  0.612930
2013-01-01 00:25:00 -0.353999
2013-01-01 00:26:00  1.431318
2013-01-01 00:27:00  0.184914
2013-01-01 00:28:00  0.187825
2013-01-01 00:29:00 -0.142211
...                       ...
2013-03-11 10:10:00  0.389272
2013-03-11 10:11:00  1.319523
2013-03-11 10:12:00 -1.304544
2013-03-11 10:13:00  0.408443
2013-03-11 10:14:00  0.413435
2013-03-11 10:15:00  0.668941
2013-03-11 10:16:00 -0.060149
2013-03-11 10:17:00 -0.393147
2013-03-11 10:18:00 -0.528606
2013-03-11 10:19:00  0.088649
2013-03-11 10:20:00 -0.221874
2013-03-11 10:21:00  0.120585
2013-03-11 10:22:00 -0.053737
2013-03-11 10:23:00 -1.086561
2013-03-11 10:24:00 -0.279749
2013-03-11 10:25:00  0.041994
2013-03-11 10:26:00  0.136192
2013-03-11 10:27:00 -0.507726
2013-03-11 10:28:00 -1.338006
2013-03-11 10:29:00  0.104688
2013-03-11 10:30:00 -1.138785
2013-03-11 10:31:00 -0.367065
2013-03-11 10:32:00  0.639003
2013-03-11 10:33:00 -1.208152
2013-03-11 10:34:00 -1.082066
2013-03-11 10:35:00  0.084264
2013-03-11 10:36:00  2.671631
2013-03-11 10:37:00  1.260118
2013-03-11 10:38:00  0.338230
2013-03-11 10:39:00 -1.292146

[100000 rows x 1 columns]
----------------------------------------------------------------------------------------------------
                            A
2013-01-01 00:00:00 -0.242536
2013-01-01 00:01:00  0.548547
2013-01-01 00:02:00 -1.117038
2013-01-01 00:03:00  0.432176
2013-01-01 00:04:00 -0.510630
2013-01-01 00:05:00 -0.957357
2013-01-01 00:06:00  0.965401
2013-01-01 00:07:00 -1.400734
2013-01-01 00:08:00  0.578109
2013-01-01 00:09:00 -0.655137
2013-01-01 00:10:00 -1.963523
2013-01-01 00:11:00  1.283547
2013-01-01 00:12:00  1.595535
2013-01-01 00:13:00 -0.881298
2013-01-01 00:14:00 -0.100967
2013-01-01 00:15:00  0.090259
2013-01-01 00:16:00  0.776400
2013-01-01 00:17:00  0.421742
2013-01-01 00:18:00  0.240029
2013-01-01 00:19:00  0.759932
2013-01-01 00:20:00 -0.121517
2013-01-01 00:21:00  1.081618
2013-01-01 00:22:00 -0.212912
2013-01-01 00:23:00  0.184384
2013-01-01 00:24:00  0.612930
2013-01-01 00:25:00 -0.353999
2013-01-01 00:26:00  1.431318
2013-01-01 00:27:00  0.184914
2013-01-01 00:28:00  0.187825
2013-01-01 00:29:00 -0.142211
...                       ...
2013-03-11 10:10:00  0.389272
2013-03-11 10:11:00  1.319523
2013-03-11 10:12:00 -1.304544
2013-03-11 10:13:00  0.408443
2013-03-11 10:14:00  0.413435
2013-03-11 10:15:00  0.668941
2013-03-11 10:16:00 -0.060149
2013-03-11 10:17:00 -0.393147
2013-03-11 10:18:00 -0.528606
2013-03-11 10:19:00  0.088649
2013-03-11 10:20:00 -0.221874
2013-03-11 10:21:00  0.120585
2013-03-11 10:22:00 -0.053737
2013-03-11 10:23:00 -1.086561
2013-03-11 10:24:00 -0.279749
2013-03-11 10:25:00  0.041994
2013-03-11 10:26:00  0.136192
2013-03-11 10:27:00 -0.507726
2013-03-11 10:28:00 -1.338006
2013-03-11 10:29:00  0.104688
2013-03-11 10:30:00 -1.138785
2013-03-11 10:31:00 -0.367065
2013-03-11 10:32:00  0.639003
2013-03-11 10:33:00 -1.208152
2013-03-11 10:34:00 -1.082066
2013-03-11 10:35:00  0.084264
2013-03-11 10:36:00  2.671631
2013-03-11 10:37:00  1.260118
2013-03-11 10:38:00  0.338230
2013-03-11 10:39:00 -1.292146

[100000 rows x 1 columns]
----------------------------------------------------------------------------------------------------
                            A
2013-01-01 00:00:00 -0.242536
2013-01-01 00:01:00  0.548547
2013-01-01 00:02:00 -1.117038
2013-01-01 00:03:00  0.432176
2013-01-01 00:04:00 -0.510630
2013-01-01 00:05:00 -0.957357
2013-01-01 00:06:00  0.965401
2013-01-01 00:07:00 -1.400734
2013-01-01 00:08:00  0.578109
2013-01-01 00:09:00 -0.655137
2013-01-01 00:10:00 -1.963523
2013-01-01 00:11:00  1.283547
2013-01-01 00:12:00  1.595535
2013-01-01 00:13:00 -0.881298
2013-01-01 00:14:00 -0.100967
2013-01-01 00:15:00  0.090259
2013-01-01 00:16:00  0.776400
2013-01-01 00:17:00  0.421742
2013-01-01 00:18:00  0.240029
2013-01-01 00:19:00  0.759932
2013-01-01 00:20:00 -0.121517
2013-01-01 00:21:00  1.081618
2013-01-01 00:22:00 -0.212912
2013-01-01 00:23:00  0.184384
2013-01-01 00:24:00  0.612930
2013-01-01 00:25:00 -0.353999
2013-01-01 00:26:00  1.431318
2013-01-01 00:27:00  0.184914
2013-01-01 00:28:00  0.187825
2013-01-01 00:29:00 -0.142211
...                       ...
2013-02-28 23:30:00  0.149911
2013-02-28 23:31:00  0.025620
2013-02-28 23:32:00  0.880351
2013-02-28 23:33:00  1.883384
2013-02-28 23:34:00 -0.577314
2013-02-28 23:35:00  1.518246
2013-02-28 23:36:00 -1.860227
2013-02-28 23:37:00 -0.518418
2013-02-28 23:38:00  0.312917
2013-02-28 23:39:00  0.806508
2013-02-28 23:40:00  0.666677
2013-02-28 23:41:00  1.659698
2013-02-28 23:42:00 -0.210612
2013-02-28 23:43:00 -0.723852
2013-02-28 23:44:00  0.183034
2013-02-28 23:45:00  1.453876
2013-02-28 23:46:00  1.396061
2013-02-28 23:47:00  0.349081
2013-02-28 23:48:00 -0.487514
2013-02-28 23:49:00 -0.555732
2013-02-28 23:50:00  0.087211
2013-02-28 23:51:00 -0.969240
2013-02-28 23:52:00 -0.518785
2013-02-28 23:53:00  0.436958
2013-02-28 23:54:00  0.868221
2013-02-28 23:55:00 -0.171485
2013-02-28 23:56:00  1.133983
2013-02-28 23:57:00 -0.106949
2013-02-28 23:58:00 -1.179649
2013-02-28 23:59:00  1.713476

[84960 rows x 1 columns]
----------------------------------------------------------------------------------------------------
                            A
2013-01-01 00:00:00 -0.242536
2013-01-01 00:01:00  0.548547
2013-01-01 00:02:00 -1.117038
2013-01-01 00:03:00  0.432176
2013-01-01 00:04:00 -0.510630
2013-01-01 00:05:00 -0.957357
2013-01-01 00:06:00  0.965401
2013-01-01 00:07:00 -1.400734
2013-01-01 00:08:00  0.578109
2013-01-01 00:09:00 -0.655137
2013-01-01 00:10:00 -1.963523
2013-01-01 00:11:00  1.283547
2013-01-01 00:12:00  1.595535
2013-01-01 00:13:00 -0.881298
2013-01-01 00:14:00 -0.100967
2013-01-01 00:15:00  0.090259
2013-01-01 00:16:00  0.776400
2013-01-01 00:17:00  0.421742
2013-01-01 00:18:00  0.240029
2013-01-01 00:19:00  0.759932
2013-01-01 00:20:00 -0.121517
2013-01-01 00:21:00  1.081618
2013-01-01 00:22:00 -0.212912
2013-01-01 00:23:00  0.184384
2013-01-01 00:24:00  0.612930
2013-01-01 00:25:00 -0.353999
2013-01-01 00:26:00  1.431318
2013-01-01 00:27:00  0.184914
2013-01-01 00:28:00  0.187825
2013-01-01 00:29:00 -0.142211
...                       ...
2013-02-28 23:30:00  0.149911
2013-02-28 23:31:00  0.025620
2013-02-28 23:32:00  0.880351
2013-02-28 23:33:00  1.883384
2013-02-28 23:34:00 -0.577314
2013-02-28 23:35:00  1.518246
2013-02-28 23:36:00 -1.860227
2013-02-28 23:37:00 -0.518418
2013-02-28 23:38:00  0.312917
2013-02-28 23:39:00  0.806508
2013-02-28 23:40:00  0.666677
2013-02-28 23:41:00  1.659698
2013-02-28 23:42:00 -0.210612
2013-02-28 23:43:00 -0.723852
2013-02-28 23:44:00  0.183034
2013-02-28 23:45:00  1.453876
2013-02-28 23:46:00  1.396061
2013-02-28 23:47:00  0.349081
2013-02-28 23:48:00 -0.487514
2013-02-28 23:49:00 -0.555732
2013-02-28 23:50:00  0.087211
2013-02-28 23:51:00 -0.969240
2013-02-28 23:52:00 -0.518785
2013-02-28 23:53:00  0.436958
2013-02-28 23:54:00  0.868221
2013-02-28 23:55:00 -0.171485
2013-02-28 23:56:00  1.133983
2013-02-28 23:57:00 -0.106949
2013-02-28 23:58:00 -1.179649
2013-02-28 23:59:00  1.713476

[84960 rows x 1 columns]
----------------------------------------------------------------------------------------------------
                            A
2013-01-01 00:00:00 -0.242536
2013-01-01 00:01:00  0.548547
2013-01-01 00:02:00 -1.117038
2013-01-01 00:03:00  0.432176
2013-01-01 00:04:00 -0.510630
2013-01-01 00:05:00 -0.957357
2013-01-01 00:06:00  0.965401
2013-01-01 00:07:00 -1.400734
2013-01-01 00:08:00  0.578109
2013-01-01 00:09:00 -0.655137
2013-01-01 00:10:00 -1.963523
2013-01-01 00:11:00  1.283547
2013-01-01 00:12:00  1.595535
2013-01-01 00:13:00 -0.881298
2013-01-01 00:14:00 -0.100967
2013-01-01 00:15:00  0.090259
2013-01-01 00:16:00  0.776400
2013-01-01 00:17:00  0.421742
2013-01-01 00:18:00  0.240029
2013-01-01 00:19:00  0.759932
2013-01-01 00:20:00 -0.121517
2013-01-01 00:21:00  1.081618
2013-01-01 00:22:00 -0.212912
2013-01-01 00:23:00  0.184384
2013-01-01 00:24:00  0.612930
2013-01-01 00:25:00 -0.353999
2013-01-01 00:26:00  1.431318
2013-01-01 00:27:00  0.184914
2013-01-01 00:28:00  0.187825
2013-01-01 00:29:00 -0.142211
...                       ...
2013-02-27 23:31:00 -1.726969
2013-02-27 23:32:00 -1.358433
2013-02-27 23:33:00  0.204934
2013-02-27 23:34:00  0.031384
2013-02-27 23:35:00 -0.494653
2013-02-27 23:36:00  0.143950
2013-02-27 23:37:00  0.354126
2013-02-27 23:38:00  0.155729
2013-02-27 23:39:00  1.576099
2013-02-27 23:40:00 -0.502740
2013-02-27 23:41:00  0.200951
2013-02-27 23:42:00 -1.063408
2013-02-27 23:43:00  0.363678
2013-02-27 23:44:00  0.781551
2013-02-27 23:45:00  1.001358
2013-02-27 23:46:00  1.036128
2013-02-27 23:47:00  0.657713
2013-02-27 23:48:00  1.310911
2013-02-27 23:49:00 -1.471951
2013-02-27 23:50:00  1.064006
2013-02-27 23:51:00 -1.644589
2013-02-27 23:52:00 -0.149205
2013-02-27 23:53:00  0.157785
2013-02-27 23:54:00  0.112255
2013-02-27 23:55:00 -0.520070
2013-02-27 23:56:00  0.074072
2013-02-27 23:57:00 -0.497157
2013-02-27 23:58:00 -0.662016
2013-02-27 23:59:00 -0.359146
2013-02-28 00:00:00 -0.062612

[83521 rows x 1 columns]
----------------------------------------------------------------------------------------------------
                            A
2013-01-15 00:00:00 -0.643699
2013-01-15 00:01:00 -1.606482
2013-01-15 00:02:00  1.865438
2013-01-15 00:03:00 -1.068794
2013-01-15 00:04:00  0.534539
2013-01-15 00:05:00 -0.078451
2013-01-15 00:06:00 -0.677260
2013-01-15 00:07:00  0.331717
2013-01-15 00:08:00  0.566541
2013-01-15 00:09:00  1.870844
2013-01-15 00:10:00  0.521330
2013-01-15 00:11:00 -0.709766
2013-01-15 00:12:00  0.287158
2013-01-15 00:13:00 -0.913932
2013-01-15 00:14:00 -0.019699
2013-01-15 00:15:00 -1.038387
2013-01-15 00:16:00  0.209784
2013-01-15 00:17:00 -0.587934
2013-01-15 00:18:00  0.565923
2013-01-15 00:19:00  0.311065
2013-01-15 00:20:00 -1.076385
2013-01-15 00:21:00  0.618378
2013-01-15 00:22:00  0.761367
2013-01-15 00:23:00  1.241642
2013-01-15 00:24:00  0.734976
2013-01-15 00:25:00  0.419479
2013-01-15 00:26:00 -0.089792
2013-01-15 00:27:00 -0.079159
2013-01-15 00:28:00  1.437806
2013-01-15 00:29:00 -0.883364
...                       ...
2013-01-15 12:01:00 -1.736734
2013-01-15 12:02:00  0.105008
2013-01-15 12:03:00 -1.428030
2013-01-15 12:04:00 -1.838228
2013-01-15 12:05:00 -2.747091
2013-01-15 12:06:00  0.560108
2013-01-15 12:07:00 -0.554414
2013-01-15 12:08:00  0.045224
2013-01-15 12:09:00  0.273188
2013-01-15 12:10:00 -1.351477
2013-01-15 12:11:00  0.540966
2013-01-15 12:12:00 -0.185873
2013-01-15 12:13:00 -0.450923
2013-01-15 12:14:00 -0.197761
2013-01-15 12:15:00 -2.297449
2013-01-15 12:16:00  0.272048
2013-01-15 12:17:00 -0.473221
2013-01-15 12:18:00  1.005759
2013-01-15 12:19:00  0.627865
2013-01-15 12:20:00  1.180488
2013-01-15 12:21:00  0.170868
2013-01-15 12:22:00  2.330831
2013-01-15 12:23:00 -0.524926
2013-01-15 12:24:00  0.730915
2013-01-15 12:25:00 -0.102084
2013-01-15 12:26:00 -0.599698
2013-01-15 12:27:00 -0.324082
2013-01-15 12:28:00 -0.687907
2013-01-15 12:29:00 -0.664396
2013-01-15 12:30:00  1.024526

[751 rows x 1 columns]

In [37]:
dft2 = pd.DataFrame(np.random.randn(20, 1),
                    columns = ["A"],
                    index = pd.MultiIndex.from_product([
                        pd.date_range("20130101", periods = 10, freq = "12H"),
                        ["a", "b"]
                    ]))
print(dft2)
print("-" * 100)

try:
    print(dft2["2013-01-05"])
except:
    print("ERROR")
print("-" * 100)

print(dft2.loc["2013-01-05"])
print("-" * 100)

dft2 = dft2.swaplevel(0, 1).sort_index()
print(dft2)
print("-" * 100)

idx = pd.IndexSlice
print(dft2.loc[idx[:, "2013-01-05"], :])

                              A
2013-01-01 00:00:00 a -0.866774
                    b -0.930500
2013-01-01 12:00:00 a -0.026939
                    b  1.313407
2013-01-02 00:00:00 a  1.138884
                    b -0.593830
2013-01-02 12:00:00 a -1.465060
                    b -0.495297
2013-01-03 00:00:00 a  1.009147
                    b  0.310987
2013-01-03 12:00:00 a -0.808627
                    b -1.626384
2013-01-04 00:00:00 a -0.143131
                    b -0.828087
2013-01-04 12:00:00 a -1.048906
                    b  0.360801
2013-01-05 00:00:00 a  0.446044
                    b -1.093575
2013-01-05 12:00:00 a -0.528344
                    b  1.119421
----------------------------------------------------------------------------------------------------
ERROR
----------------------------------------------------------------------------------------------------
                              A
2013-01-05 00:00:00 a  0.446044
                    b -1.093575
2013-01-05 12:00:00 a -0.528344
                    b  1.119421
----------------------------------------------------------------------------------------------------
                              A
a 2013-01-01 00:00:00 -0.866774
  2013-01-01 12:00:00 -0.026939
  2013-01-02 00:00:00  1.138884
  2013-01-02 12:00:00 -1.465060
  2013-01-03 00:00:00  1.009147
  2013-01-03 12:00:00 -0.808627
  2013-01-04 00:00:00 -0.143131
  2013-01-04 12:00:00 -1.048906
  2013-01-05 00:00:00  0.446044
  2013-01-05 12:00:00 -0.528344
b 2013-01-01 00:00:00 -0.930500
  2013-01-01 12:00:00  1.313407
  2013-01-02 00:00:00 -0.593830
  2013-01-02 12:00:00 -0.495297
  2013-01-03 00:00:00  0.310987
  2013-01-03 12:00:00 -1.626384
  2013-01-04 00:00:00 -0.828087
  2013-01-04 12:00:00  0.360801
  2013-01-05 00:00:00 -1.093575
  2013-01-05 12:00:00  1.119421
----------------------------------------------------------------------------------------------------
                              A
a 2013-01-05 00:00:00  0.446044
  2013-01-05 12:00:00 -0.528344
b 2013-01-05 00:00:00 -1.093575
  2013-01-05 12:00:00  1.119421

### 7.Resapling